#!/bin/bash
# -*- sh -*-

if [ $# -lt 1 ] ; then
    echo "Usage: $0 singlelongstring"
fi
echo "$1" \
    | tr ' ' '\n' \
    | awk '{s=0} NF==0 {s=1} s==0 {print}' \
    | awk 'BEGIN{ d=0} d==1 { print "-D " $0; d=2} /-D/ {d=1} d==0 {print $0} d==2 {d=0}' \
    | awk 'NR==1 {print $0} NR>1 {print "    " $0 } '

