#!/bin/bash
################################################################
####
#### script for parsing a line and finding mention of a library in it
#### great for really long link lines
####
#### probable use:
#### make myprogram | xargs findlib metis
####
################################################################


if [ $# -lt 1 ] ; then
  echo "Usage: $0 pathname"
  echo "not: $*"
  exit 0
fi

path=$1
##echo $path
eval path=\${${path}}
##echo $path

for p \
    in $( echo $path | sed -e 's/:/ /g' ) ; do 
    echo $p 
done
